### ISSUE TITLE
porch: git access parameters do not follow changes in the porch Repository object

### ISSUE THREAD

**Issue by kispaljr** [nephio-project/nephio#532] opened 2024-02-21 12:15 UTC
I encountered the following issue that seems to be a bug in the git client handling in porch:

1.  `Repository.config.porch.kpt.dev` object created with missing `secretRef` field
2. `kpt alpha rpkg init ...` command fails with message: `Error: Internal error occurred: authentication required`
3. Correct  `secretRef` info is patched into the Repository (with `kubectl apply`)
4.  `kpt alpha rpkg init ...` command fails with the same message: `Error: Internal error occurred: authentication required`
5. Repository object is deleted and the recreated with the same contents
6. `kpt alpha rpkg init ...` command succeeds

**Comment by kispaljr** [comment] 2024-03-01 21:16
This seems to be a duplicate of https://github.com/kptdev/kpt/issues/4088
Sorry.
Should I leave the issue open anyway, considering that eventually we want to track porch issues under Nephio, not under kpt?

**Comment by johnbelamaric** [comment] 2024-03-04 17:22
Yeah, we should move them here. Moving issues from one org to a different org is not something that is natively supported by GitHub. But it looks like there are some workarounds in the comments here (I have not tried any of these): https://github.com/orgs/community/discussions/5766

**Comment by liamfallon** [comment] 2024-05-17 00:55
Triaged

**Comment by kushnaidu** [comment] 2024-06-20 12:22
I cannot reproduce the issue any more and won't create a PR for this issue. 
My findings are as follows,

Repository created without secretref - 
![created repo with no credentials](https://github.com/nephio-project/nephio/assets/159911459/a2de0740-e3e8-4aa8-a4a2-2a242c5d2c92)

porchctl command throws error with auth failed -
![error with init command](https://github.com/nephio-project/nephio/assets/159911459/6e30c91e-ecf3-4446-9a3c-40296a04ffca)

Update repo and init again with porchctl - 
![patch repo and init](https://github.com/nephio-project/nephio/assets/159911459/c76c367c-9d5c-4cfd-80c1-4a2a5b92a979)
The command succeeds without any issue.

Same tried with kpt alpha and without any issue - 
![kpt](https://github.com/nephio-project/nephio/assets/159911459/46d0f310-da81-4626-b5e2-3b6d33e8c047)

**Comment by kushnaidu** [comment] 2024-06-20 12:26
Closing the ticket.

**Closed by kushnaidu** 2024-06-20 12:26 UTC
Labels: bug, area/package-management, area/porch, area/platform, triaged
