### ISSUE TITLE
E2E Testing : Test to scaling UPF instance by vertically scaling an individual Pod

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#239] opened 2023-05-30 15:26 UTC
Test the config changes to the capacity requirement results in bigger pods

**Comment by johnbelamaric** [comment] 2023-06-02 16:23
@denysaleksandrov - manually testing is done, this works

We need to add e2e test to exercise this.

**Comment by johnbelamaric** [comment] 2023-06-08 22:36
The test should be added to our [e2e](https://github.com/nephio-project/test-infra/tree/main/e2e/tests) as test case 008.sh.

**Comment by rravindran123** [comment] 2023-06-09 17:44
Don't think there is a PR for 008.sh yet, will wait for it before i run the test

**Comment by johnbelamaric** [comment] 2023-06-09 23:47
Ok, thanks! Would you want to take a crack at writing that? It would be very similar to what we need to do for SMF here: https://github.com/nephio-project/nephio/issues/240#issuecomment-1585284084

**Comment by rravindran123** [comment] 2023-06-10 00:02
Sure, I can, so just to confirm is UPF deployment is working ?, from today's call looks like there are some issues with fn pipeline execution ?

**Comment by johnbelamaric** [comment] 2023-06-10 00:21
Nope, not working yet. So you can't really test it. But you could have the test script written. I suspect the Porch bug described in the linked comment is going to need to be fixed, though.

**Comment by rravindran123** [comment] 2023-06-10 01:40
Sure  , guess it the Capacity/maxUplinkThroughput: 10G , maxDownlinkThroughput: 10G, needs to be reset, but to what value ?, will have my sandbox set-up up and try , https://github.com/nephio-project/test-infra/blob/main/e2e/tests/001.sh, guss this has similar steps, and use the same kpt fn ?

**Comment by johnbelamaric** [comment] 2023-06-10 01:43
You can either use a kpt fn like "search-replace" or just edit the file with something like "sed" or "yq" or something. Kpt fn are good for complex edits but there is nothing wrong with a simple edit.

**Comment by johnbelamaric** [comment] 2023-06-10 01:55
Not sure what capacity will trigger a change, have task the team.

**Comment by rravindran123** [comment] 2023-06-10 23:35
Sure,  will check the existing scripts and play around a bit, will update this thread..

**Comment by rravindran123** [comment] 2023-06-11 21:06
@johnbelamaric , this is a skeleton script, i only tested the search-replace kpt-fn, mostly followed the 001.sh
```
#!/bin/bash

# Set the new value for maxUplinkThroughput as a parameter
new_capacity_value=$1

set -o pipefail
set -o errexit
set -o nounset
[[ "${DEBUG:-false}" != "true" ]] || set -o xtrace

export HOME=${HOME:-/home/ubuntu/}
export E2EDIR=${E2EDIR:-$HOME/test-infra/e2e}
export TESTDIR=${TESTDIR:-$E2EDIR/tests}
export LIBDIR=${LIBDIR:-$E2EDIR/lib}

source "${LIBDIR}/k8s.sh"

kubeconfig="$HOME/.kube/config"

upf_deployment_pkg=$(kpt alpha rpkg get --name free5gc-packages  --revision v3 -o jsonpath='{.metadata.name}')

upf_pkg_rev=$(kpt alpha rpkg clone -n default "$upf_deployment_pkg" --repository mgmt edge01 | cut -f 3 -d ' ')

kpt alpha rpkg pull -n default "upf_pkg_rev" edge01_upf_scaling

kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.2.0 edge01_upf_scaling -- by-path='spec.maxUplinkThroughput' by-value=10G put-value=$new_capacity_value
kpt fn eval --image gcr.io/kpt-fn/search-replace:v0.2.0 edge01_upf_scaling -- by-path='spec.maxDownlinkThroughput' by-value=10G put-value=$new_capacity_value

kpt alpha rpkg push -n default "$upf_pkg_rev" edge01

kpt alpha rpkg propose -n default "$upf_pkg_rev"

kpt alpha rpkg approve -n default "$upf_pkg_rev"

kubectl get secret edge01-kubeconfig -o jsonpath='{.data.value}' | base64 -d > edge01-kubeconfig

k8s_wait_exists "edge01-kubeconfig" 600 "free5gc-upf" "deployment" "free5gc-upf"

k8s_wait_ready "edge01-kubeconfig" 600 "free5gc-upf" "deployment" "free5gc-upf"
```

**Comment by rravindran123** [comment] 2023-06-11 21:23
Guess, this is not correct, the package needs to come from edge01 deployment repo, instead of new clone..but please comment

**Comment by johnbelamaric** [comment] 2023-06-11 21:38
Nice, that's a good start. Can you create a PR with it, then we can review it line-by-line? Basically, we have two choices:

1. We could tweak the capacity of the *entire* fleet of UPFs. The problem is, since we deployed *directly* from free5gc-packages, this hard. To do this, we would have been better cloning the upf package from free5gc-packages into an "organizaitonal" or "team" repository, and basing our PackageVariantSet off of that. Then, we could modify the clone and it would update all the fanned-out packages.
2. We could tweak *one* instance - like edge01. I think that's what you are suggesting, and that's fine. 

To do that, the main difference is instead of:

```
upf_deployment_pkg=$(kpt alpha rpkg get --name free5gc-packages  --revision v3 -o jsonpath='{.metadata.name}')

upf_pkg_rev=$(kpt alpha rpkg clone -n default "$upf_deployment_pkg" --repository mgmt edge01 | cut -f 3 -d ' ')
```

what you want to do is find the package revision name for the specific instance in the edge01 repo. I am not sure the `kpt alpha rpkg` commands are sufficiently expressive, you may have to just do something like:

```
upf_pkg_rev=$(kpt alpha rpkg get --name free5gc-upf | grep edge01 | grep latest | cut -d ' ' -f 1)
```

That's untested - but the idea is to pull out all the package revisions with the right package name and use grep and cut to find the package revision name.

Then, you use `kpt alpha rpkg copy $upf_pkg_rev` to create a new Draft on the server; then use `kpt alpha rpkg pull` to get that package revision.

**Comment by rravindran123** [comment] 2023-06-12 02:50
Sure, was scoping only for one cluster for now, will push a PR and we can iterate on that.

**Comment by rravindran123** [comment] 2023-06-12 04:17
https://github.com/nephio-project/test-infra/pull/80/files

**Comment by rravindran123** [comment] 2023-06-13 17:10
Ok sure, see that, in the blueprint package, it is set to 10G, so thought was the threshold.
https://github.com/nephio-project/free5gc-packages/blob/main/pkg-example-upf-bp/capacity.yaml

**Comment by johnbelamaric** [comment] 2023-06-16 01:10
Fixed by https://github.com/nephio-project/test-infra/pull/80

**Closed by johnbelamaric** 2023-06-16 01:10 UTC
Labels: area/package-management, sig/automation
