### ISSUE TITLE
PackageRevision label selection does not work

### ISSUE THREAD

**Issue by liamfallon** [nephio-project/nephio#690] opened 2024-04-08 13:39 UTC
Original issue URL: https://github.com/kptdev/kpt/issues/3401
Original issue user: https://github.com/johnbelamaric
Original issue created at: 2022-07-21T19:45:49Z
Original issue last updated at: 2023-01-26T04:12:11Z
Original issue body: ### Expected behavior
I can use `kubectl get packagerevision -l 'kpt.dev/latest-revision=true'` to see the latest version of the packages.

### Actual behavior
All package revisions are returned. I suspect this is because it's an aggregated API server so we would have to implement this ourselves (maybe another reason to use CRDs instead):

```
jbelamaric@jbelamaric:~/proj/nephio-dev-deploy$ k get packagerevision -l 'kpt.dev/latest-revision=true' -n default
NAME                                                         PACKAGE           REVISION   LATEST   LIFECYCLE   REPOSITORY
nephio-dev-deploy-6fe89b83a578123d9bd58556360555c30676e0d1   dnscache          main       false    Published   nephio-dev-deploy
nephio-dev-deploy-ecbbc233c9caa49916422f5a35f770f17eebed4d   dnscache          v1         true     Published   nephio-dev-deploy
nephio-dev-deploy-0247f2adfd09fa113737ab033918095bdfaf16eb   dnscache          v2         false    Draft       nephio-dev-deploy
nephio-packages-e01d890d4c85fc62299d956829ffe948d712bd76     coredns-caching   main       false    Published   nephio-packages
nephio-packages-1324babaaf974f13daea7cb675934ab8a616ed89     coredns-caching   v0.1       false    Published   nephio-packages
nephio-packages-edfea244e9255e476de3dcc00b56003104f1d4cd     coredns-caching   v1         false    Published   nephio-packages
nephio-packages-8f6ade1048c5a7da0d8364d5c82026339f4950ad     coredns-caching   v2         false    Published   nephio-packages
nephio-packages-903eb7670936cc2ba4d5f6325ab9f15da80bc5c8     coredns-caching   v3         false    Published   nephio-packages
nephio-packages-85e491a3bbf7203345e75cb7dd76ae7e3b07c21e     coredns-caching   v4         true     Published   nephio-packages
```

### Steps to reproduce the behavior

Original issue comments:
Comment user: https://github.com/mortent
Comment created at: 2023-01-26T04:12:11Z
Comment last updated at: 2023-01-26T04:12:11Z
Comment body: Yeah, since we are looking to migrate to CRDs, we probably want to hold off on this until then.

**Comment by kushnaidu** [comment] 2024-05-29 10:36
I cannot reproduce the issue. 

![image](https://github.com/nephio-project/nephio/assets/159911459/26e08bde-4c62-4d05-b40e-a511c148a423)

Issue seems to fixed. 
https://github.com/Nordix/porch/blob/a03a8d2379b5f76a0da9b4123edb75f1b906ab83/pkg/registry/porch/packagecommon.go#L84

**Comment by kushnaidu** [comment] 2024-06-05 09:58
The issue is already fixed and reproducible. closing the ticket.

**Closed by kushnaidu** 2024-06-05 09:58 UTC
Labels: bug, area/porch, area/platform
